# Generated by Django 2.1.15 on 2022-04-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_email',
            field=models.EmailField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_added',
            field=models.DateTimeField(verbose_name='date added'),
        ),
    ]
