# Generated by Django 2.1.15 on 2022-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20220429_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photos',
        ),
        migrations.AddField(
            model_name='listing',
            name='photo1',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo2',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo3',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo4',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo5',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ber_rating',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='features',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_map',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
