# Generated by Django 2.1.15 on 2022-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20220429_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
