# Generated by Django 2.1.15 on 2022-04-29 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20220429_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
    ]
