# Generated by Django 2.1.15 on 2022-04-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='property_map',
        ),
        migrations.AddField(
            model_name='listing',
            name='rekognition_features',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ber_rating',
            field=models.CharField(default='A1', max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_email',
            field=models.EmailField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='features',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo1',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo2',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo3',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo4',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo5',
            field=models.FileField(upload_to='media/'),
        ),
    ]
