# Generated by Django 2.1.15 on 2022-04-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20220429_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(default='0', max_length=5000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='features',
            field=models.CharField(default='0', max_length=5000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rekognition_features',
            field=models.CharField(default='none', max_length=5000),
        ),
    ]
